sudo: false

language: java

services:
  - docker

addons:
  hosts:
    -db

install:
  -docker build -t database db/.
  -docker run --rm -d -e MYSQL_ROOT_PASSWORD=example -p 33060:3306 database
  -mvn install -DskipTests=true -DMaven.javadoc.skip=true -B -V

before_script: :
  -mvn clean

jobs:
  include:
    - stage: integration tests
      jdk: oraclejdk11
      script: echo "Integration Tests"
    - stage: deploy
      install: skip
      jdk: oraclejdk11
      script: echo "Deploy"

stages:
  -integration tests
  -name: deploy
  if: branch = master
after_success:
  - docker-compose up --abort-on-container-exit